config/routes.rb
Rails.application.routes.draw do
  get '/' => "site#home"

    resources :items do
    resources :bids
  end
    resources :users

end

app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :item
	belongs_to :user

	validates :price, presence: true, numericality: true
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :bids

	validates :name, presence: true
	validates :price, presence: true, numericality: true
	validates :expire, presence: true

	has_attached_file :logo, styles: {:medium => "300x300>", :thumb => "130x130>"}
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :bids

	validates :name, presence: true
	validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
	def index
		@item = Item.find params[:item_id]
		@total_amount = 

	end
	def new
		@bid = Bid.new
	end
	def create
		@bid = Bid.new 
	end
end

# 		@project = Project.find params[:project_id]
# 		@entries = @project.entries
# 		@entries_by_month = @project.entries_by_month(2015, 2)
# 		total_hours = 0
# 		@entries_by_month.each {|entry| total_hours += entry.hours}
# 		@hours = total_hours

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@item = Item.all
	end
	def show
		@item = Item.find(params[:id])
	end
	def new
		@item = Item.new
	end
	def create
		@item = Item.new item_params
		if @item.save
			redirect_to items_path
		else
			render 'new'
		end
	end
	def edit
		@item = Item.find(params[:id])
	end
	def update
		@item = Item.find(params[:id])
		@item.update_attributes item_params
	end
	private
	def item_params
		params.require(:item).permit(:name, :price, :expire, :logo)
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new user_params
		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end
	private
	def user_params
		params.require(:user).permit(:name, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bids/index.html.erb
<h3>display item</h3>
<ul>
	<% @item.each do |item|%>
	<li><%= item.name%></li>
	<li><%= item.price%></li>
	<%end%>
</ul>

app/views/bids/new.html.erb
<%= form_for @bid do |f|%>
	<%= f.label "€" %>
	<%= f.number_field :amount, placeholder: "99,99" %>
<%end%>

app/views/items/_itemform.html.erb
<%= form_for @item, :html => { :multipart => true } do |f|%>
	<%= f.label :name%>
	<%= f.text_field :name%>
	<br>
	<%= f.label :price%>
	<%= f.text_field :price%>
	<br>
	<%= f.label :expire%>
	<%= f.date_field :expire%>
	<br>
	<%= f.label :logo%>
	<%= f.file_field :logo%>
	<br>
	<%= f.submit 'Add item'%>
<%end%>
<%= link_to("back", items_path)%>

app/views/items/index.html.erb
<h2>Display item</h2>
<ul>
	<% @item.each do |item|%>
	<li><h3><%= link_to(item.name, item_bids_path(:item_id))%></h3><br>
	<%= image_tag item.logo.url(:thumb)%><br>
	</li>
	<hr>
	<%end%>
</ul>
<br>

<%= link_to("add new item", new_item_path)%>

app/views/items/new.html.erb
<%if @item.errors.any? %>
	<ul>
		<% @item.errors.full_messages.each do |errors_msg| %>
		<li><%= errors_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @item, :html => { :multipart => true } do |f|%>
	<%= f.label :name%>
	<%= f.text_field :name%>
	<br>
	<%= f.label :price%>
	<%= f.text_field :price%>
	<br>
	<%= f.label :expire%>
	<%= f.date_field :expire%>
	<br>
	<%= f.label :logo%>
	<%= f.file_field :logo%>
	<br>
	<%= f.submit 'Add item'%>
<%end%>
<%= link_to("back", items_path)%>

app/views/items/show.html.erb
<h2>item</h2>
<%= @item%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auctions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header><h1>Welcome to the Auction</h1></header>
<%= yield %>

</body>
</html>

app/views/site/home.html.erb
<h2>follow the link to enter the <%= link_to("Auction", items_path)%></h2>

app/views/users/_userform.html.erb
<%= form_for @user do |f|%>
	<%= f.label :name%>
	<%= f.text_field :name%>
	<br>
	<%= f.label :email%>
	<%= f.text_field :email%>
	<br>
	<%= f.submit 'Done'%>
	<%end%>

app/views/users/index.html.erb
<h2>users</h2>
<% @user.each do |user|%>
<%= user.name%><br>
<%end%>

app/views/users/new.html.erb
<%if @user.errors.any? %>
	<ul>
		<% @user.errors.full_messages.each do |errors_msg| %>
		<li><%= errors_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= render 'userform'%>